version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar
